[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zshrc"
    refreshPeriod = "168h"
[".zsh/aliases.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/aliases.zsh"
    refreshPeriod = "168h"
[".zsh/functions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/functions.zsh"
    refreshPeriod = "168h"
[".zsh/fzf.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/fzf.zsh"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/hthntts/nvim.git"
    refreshPeriod = "168h"
[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/tmux/master/.tmux.conf"
    refreshPeriod = "168h"
[".doom.d"]
    type = "git-repo"
    url = "https://github.com/hthntts/doomemacs.git"
    refreshPeriod = "168h"
