[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zshrc"
    refreshPeriod = "168h"
[".zsh/aliases.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/aliases.zsh"
    refreshPeriod = "168h"
[".zsh/functions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/functions.zsh"
    refreshPeriod = "168h"
[".zsh/fzf.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/zsh/master/.zsh/fzf.zsh"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    refreshPeriod = "168h"
[".zsh.plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/hthntts/nvim.git"
    refreshPeriod = "168h"
[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/tmux/master/.tmux.conf"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "168h"
[".tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-yank.git"
    refreshPeriod = "168h"
[".doom.d"]
    type = "git-repo"
    url = "https://github.com/hthntts/doomemacs.git"
    refreshPeriod = "168h"
[".config/karabiner/karabiner.json"]
    type = "file"
    url = "https://gist.githubusercontent.com/hthntts/95e0bd033b190efea0266bf19a46267e/raw/c0ea5b058aeb5f8c3183fda363a5bca1240500aa/karabiner"
    refreshPeriod = "168h"
